services:
  db:
    image: mysql:8.0
    container_name: album-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: album_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - ./mysql_data:/var/lib/mysql